---
repos:
  - repo: local
    hooks:
      - id: repo-tools-ci-lint
        name: Repo tools CI lint
        entry: bash tests/repo_tools/ci-lint.sh
        language: system
        pass_filenames: false
