---
rules:
  - id: web-app-get-js
    language: JavaScript
    rule:
      pattern: "app.get($PATH, $HANDLER)"
    message: "HTTP GET route (app)"
  - id: web-app-get-ts
    language: TypeScript
    rule:
      pattern: "app.get($PATH, $HANDLER)"
    message: "HTTP GET route (app)"
  - id: web-app-post-js
    language: JavaScript
    rule:
      pattern: "app.post($PATH, $HANDLER)"
    message: "HTTP POST route (app)"
  - id: web-app-post-ts
    language: TypeScript
    rule:
      pattern: "app.post($PATH, $HANDLER)"
    message: "HTTP POST route (app)"
  - id: web-app-put-js
    language: JavaScript
    rule:
      pattern: "app.put($PATH, $HANDLER)"
    message: "HTTP PUT route (app)"
  - id: web-app-put-ts
    language: TypeScript
    rule:
      pattern: "app.put($PATH, $HANDLER)"
    message: "HTTP PUT route (app)"
  - id: web-app-patch-js
    language: JavaScript
    rule:
      pattern: "app.patch($PATH, $HANDLER)"
    message: "HTTP PATCH route (app)"
  - id: web-app-patch-ts
    language: TypeScript
    rule:
      pattern: "app.patch($PATH, $HANDLER)"
    message: "HTTP PATCH route (app)"
  - id: web-app-delete-js
    language: JavaScript
    rule:
      pattern: "app.delete($PATH, $HANDLER)"
    message: "HTTP DELETE route (app)"
  - id: web-app-delete-ts
    language: TypeScript
    rule:
      pattern: "app.delete($PATH, $HANDLER)"
    message: "HTTP DELETE route (app)"
  - id: web-router-get-js
    language: JavaScript
    rule:
      pattern: "router.get($PATH, $HANDLER)"
    message: "HTTP GET route (router)"
  - id: web-router-get-ts
    language: TypeScript
    rule:
      pattern: "router.get($PATH, $HANDLER)"
    message: "HTTP GET route (router)"
  - id: web-router-route-get-js
    language: JavaScript
    rule:
      pattern: "router.route($PATH).get($HANDLER)"
    message: "HTTP GET route (router.route)"
  - id: web-router-route-get-ts
    language: TypeScript
    rule:
      pattern: "router.route($PATH).get($HANDLER)"
    message: "HTTP GET route (router.route)"
  - id: web-router-post-js
    language: JavaScript
    rule:
      pattern: "router.post($PATH, $HANDLER)"
    message: "HTTP POST route (router)"
  - id: web-router-post-ts
    language: TypeScript
    rule:
      pattern: "router.post($PATH, $HANDLER)"
    message: "HTTP POST route (router)"
  - id: web-router-route-post-js
    language: JavaScript
    rule:
      pattern: "router.route($PATH).post($HANDLER)"
    message: "HTTP POST route (router.route)"
  - id: web-router-route-post-ts
    language: TypeScript
    rule:
      pattern: "router.route($PATH).post($HANDLER)"
    message: "HTTP POST route (router.route)"
  - id: web-router-put-js
    language: JavaScript
    rule:
      pattern: "router.put($PATH, $HANDLER)"
    message: "HTTP PUT route (router)"
  - id: web-router-put-ts
    language: TypeScript
    rule:
      pattern: "router.put($PATH, $HANDLER)"
    message: "HTTP PUT route (router)"
  - id: web-router-patch-js
    language: JavaScript
    rule:
      pattern: "router.patch($PATH, $HANDLER)"
    message: "HTTP PATCH route (router)"
  - id: web-router-patch-ts
    language: TypeScript
    rule:
      pattern: "router.patch($PATH, $HANDLER)"
    message: "HTTP PATCH route (router)"
  - id: web-router-delete-js
    language: JavaScript
    rule:
      pattern: "router.delete($PATH, $HANDLER)"
    message: "HTTP DELETE route (router)"
  - id: web-router-delete-ts
    language: TypeScript
    rule:
      pattern: "router.delete($PATH, $HANDLER)"
    message: "HTTP DELETE route (router)"
